// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQzdEOevHE3psuB5zWyKR4BYGv-fE-KjY',
    appId: '1:415962414488:web:b7663b810d540fd1d37fed',
    messagingSenderId: '415962414488',
    projectId: 'food-data-real',
    authDomain: 'food-data-real.firebaseapp.com',
    databaseURL: 'https://food-data-real-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'food-data-real.appspot.com',
    measurementId: 'G-1HXSVBR96F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTuUEEv2WffRbd8eBl5NNzsiw4xTqsLuU',
    appId: '1:415962414488:android:98494660236e3bffd37fed',
    messagingSenderId: '415962414488',
    projectId: 'food-data-real',
    databaseURL: 'https://food-data-real-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'food-data-real.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlxT3IJyV6AvcZuNkVgVOwgt-dftKgW3g',
    appId: '1:415962414488:ios:3c6df1f56129027fd37fed',
    messagingSenderId: '415962414488',
    projectId: 'food-data-real',
    databaseURL: 'https://food-data-real-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'food-data-real.appspot.com',
    iosClientId: '415962414488-7hnl4kv4l673i6l0itnhaedr6erdfd8o.apps.googleusercontent.com',
    iosBundleId: 'com.example.fooddataagg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlxT3IJyV6AvcZuNkVgVOwgt-dftKgW3g',
    appId: '1:415962414488:ios:3c6df1f56129027fd37fed',
    messagingSenderId: '415962414488',
    projectId: 'food-data-real',
    databaseURL: 'https://food-data-real-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'food-data-real.appspot.com',
    iosClientId: '415962414488-7hnl4kv4l673i6l0itnhaedr6erdfd8o.apps.googleusercontent.com',
    iosBundleId: 'com.example.fooddataagg',
  );
}
